# Numpy Arrays

## Indexing

### Accessing 1D array

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])

In [3]:
arr[1]

2

In [4]:
arr[1] + arr[2]

5

### Accessing 2D array

In [6]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

In [8]:
print("2nd element in 1st dimension is", arr[0,1])

2nd element in 1st dimension is 2


#### Linspace

linspace(start, end, number of values between start and end)

In [9]:

np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

#### Identity matrix

In [10]:
x = np.eye(3)

In [11]:
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
x.shape

(3, 3)

#### Random numbers

np.random.randint(start_value, end_value, number_of random_intergers)

In [13]:
np.random.randint(0, 10, 10)

array([1, 7, 3, 5, 6, 3, 2, 4, 1, 8])

Generating a 2D matrix with random numbers

In [14]:
np.random.rand(3,3)

array([[0.80471099, 0.9263955 , 0.35379316],
       [0.10022755, 0.70837307, 0.1871957 ],
       [0.23713351, 0.39030352, 0.12457804]])

#### Finding maximum and minimum value in the array

In [15]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

In [16]:
arr.max()

10

Finding the index of maximum number.

In [17]:
arr.argmax()

9

In [22]:
arr.min()

1

Finding the index of minimum number.

In [20]:
arr.argmin()

0

#### Range of arrays

Returns evenly spaced value in an interval. In linspace, we specify the number of values. In range, we specify the spacing.

np.arange(start_value, end_value, spacing)

In [21]:
np.arange(0, 11, 3)

array([0, 3, 6, 9])

### Slicing

In [23]:
a = np.arange(0, 11, 2)

In [24]:
a

array([ 0,  2,  4,  6,  8, 10])

array[start_value:end_value +1]

In [25]:
a[1:3]

array([2, 4])

In [26]:
a = np.array([[1,2,3], [2,3,4], [4,5,6]])

In [27]:
a

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [28]:
a[0:1,0:2]

array([[1, 2]])

### Copy and View

The difference between copy and view is that if the original is modified the view will be modified too but the copy won't be modified.

In [29]:
z = arr.view()

In [30]:
z

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [31]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [32]:
arr[(1,3)] = 100

In [33]:
arr

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8, 100,  10]])

In [37]:
z

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8, 100,  10]])

In [39]:
b = arr.copy()
b

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8, 100,  10]])

In [41]:
arr[(1,3)] = 200
arr

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8, 200,  10]])

In [42]:
b

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8, 100,  10]])